import { Data } from "../types";
import P1 from "../assets/PACS/Biometric access control.jpg";
import P2 from "../assets/PACS/CBD office building.jpg";
import P3 from "../assets/PACS/Campus access control.jpg";
import P4 from "../assets/PACS/Parking lot entry.jpg";
import P5 from "../assets/PACS/Subway Station turnstile.jpg";
import P6 from "../assets/PACS/amusement park.jpg";

export const PAC_DATA: Data = {
  pageTitle: "PHYSICAL ACCESS CONTROL",
  pageDescription: `At ASE, we are your trusted partner in delivering top-tier solutions for Physical Access Control Systems. With a steadfast commitment to excellence, we present a diverse range of turnstiles, readers, and equipment designed to meet the unique needs of our valued clients. \n Discover the ideal access control solution tailored to your specific application needs:`,
  categories: [
    {
      productCategory: "EMPTY",
      productCategoryDescription:
        "At ASE, we are your trusted partner in delivering top-tier solutions for Physical Access Control Systems. With a steadfast commitment to excellence, we present a diverse range of turnstiles, readers, and equipment designed to meet the unique needs of our valued clients.\nDiscover the ideal access control solution tailored to your specific application needs: Our Comprehensive Solutions:",
      products: [
        {
          title: "Access Control Solutions for Office Buildings",
          description:
            "​​​​​​​​​​​​Efficiently manage building access with ASE's comprehensive solutions. Our systems include turnstiles designed for office entrances, offering multiple access methods such as RFID card, face recognition, and palm vein recognition. For visitors, we provide temporary biometric access control through RFID cards and other cutting-edge technologies.",
          imageSrc: P2,
          downloads: ["link1", "link2"],
        },
        {
          title: "Integrated Ticketing System for Amusement Parks",
          description:
            "Elevate your theme park experience with ASE's professional ticketing system. Tailored for amusement parks, our solution supports membership management, seamless financial tracking, and seamless integration with both online and offline payment systems. Gain real-time insights through comprehensive daily reports.",
          imageSrc: P6,
          downloads: ["link1", "link2"],
        },
        {
          title: "Advanced Turnstile Solutions for Subway Stations",
          description:
            "​​​​​​​​​​​​Enhance security at public spaces like subway and train stations with ASE's turnstile access control systems. Designed to align with government cloud platforms, our solutions offer a secondary development access control board for seamless integration. Experience smart pass technology with options such as identification cards, passports, and QR codes generated by local apps or custom access control systems.",
          imageSrc: P5,
          downloads: ["link1", "link2"],
        },
        {
          title: "Innovative Access Control for Campus Security",
          description:
            "Safeguard educational institutions with ASE's cutting-edge campus access control systems. Our solutions offer multifunctionality, supporting time attendance tracking and biometric access control. For added convenience, teachers and students can use specially generated QR codes from apps to access turnstiles. Manage it all through our cloud-based management software.",
          imageSrc: P3,
          downloads: ["link1", "link2"],
        },
        {
          title: "Cutting-Edge Biometric Access Control Solution",
          description:
            "Experience the future of security with ASE's state-of-the-art biometric access control system. Our offering combines unparalleled face recognition technology with a comprehensive time attendance function. Extend functionality with options like RFID cards, HID technology, QR/barcode integration, fingerprint scanning, palm vein/iris recognition, and even body temperature monitoring. Choose between LAN or cloud-based management software, and seamlessly integrate our system with your existing professional payroll and membership management software.",
          imageSrc: P1,
          downloads: ["link1", "link2"],
        },
        {
          title: "Efficient Parking Lot Entry and Exit Management",
          description:
            "ASE introduces a versatile parking system solution adaptable to various countries and parking management scenarios. Our solutions encompass a wide array of options, including LPR (License Plate Recognition) parking systems, parking turnstiles, UHF/Bluetooth-enabled systems, and ticket/card dispenser setups. Complementing these offerings is our comprehensive management software, facilitating smooth parking charging and payment procedures.",
          imageSrc: P4,
          downloads: ["link1", "link2"],
        },
      ],
    },
  ],
};
