import { Data } from "../types";
import RFID from "../assets/images/RFID-lock.jpeg";

export const PAC_DATA: Data = {
  pageTitle: "PHYSICAL ACCESS CONTROL",
  pageDescription:
    "Physical access control refers to the measures and techniques used to restrict and control access to physical spaces or resources, such as buildings, rooms, equipment, or information systems. Physical access control systems can involve a variety of tools and technologies, including locks, keys, cards, biometric sensors, and security cameras.",
  categories: [
    {
      productCategory: "Readers",
      productCategoryDescription: "This is a description of Readers",
      products: [
        {
          title: "​​​​​​​​​​​​​​CBD Office Building",
          description:
            "​​​​​​​​​​​​​Turnstile for office/building entrance, provide RFID card,face recognition , palm vein recognition, visitor temporary card access control system",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
        {
          title: "Amusement Park Ticketing System",
          description:
            "but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            biometric_sensor_type: "Optical Sensor (OP5)",
            template_extractor_matcher: "SUPREMA / ISO 19794-2 / ANSI 378",
            lfd: "LFD",
            cpu: "1.2 GHz Quad Core",
            memory: "2GB Flash + 256MB RAM",
            max_user: "500,000 (1:1), 100,000(1:N)",
            max_template:
              "1,000,000(1:1), 200,000(1:N), [1 finger =2 templates] 1,000,000 (text)",
            max_logs: "Supported",
            led: "Multi-color",
            sound: "Multi-tone buzzer",
            ethernet: "10/100 Mbps, auto MDI/MDI-X",
            "rs-485": "1ch Host or Slave (Selectable), OSDP V2.1.6",
            wiegand: "1ch Input or Output (Selectable)",
            ttl: "2ch Input",
            relay: "1 Relay",
            poe: "Supported (IEEE 802.3af compliant)",
            ingress_protection: "IP67",
            impact_protection: "IK09",
            tamper: "Supported",
            power: {
              voltage: "DC 12V",
              current: "Max. 600 mA",
            },
            operating_temperature: "-20°C ~ 50°C",
            operating_humidity: "0% ~ 80%, non-condensing",
            dimensions: "50 x 172 x 43.5mm",
            certificates: ["CE", "FCC", "KC", "RoHS", "REACH", "WEEE"],
            rf_options: [
              "125kHz HID Prox",
              "125kHz EM & 13.56MHz MIFARE, MIFARE Plus, DESFire EV1/EV2*, FeliCa, NFC",
            ],
          },
        },
        {
          title: "Subway",
          description:
            "​​​​​​​​​​​​​Turnstile for public application location like subway station,train station, airport , support government cloud platform, provide secondary development access control board to integration with government platform, smart pass with identify card ,passport, QR code generated by local Apps or other customize access control system",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
        {
          title: "Campus",
          description:
            "Karsun access control system for school, support time attendance function, biometric access control,or APPs generated special QR code for teachers and students to pass the turnstile, cloud base management software",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
        {
          title: "Bio-Access Control",
          description:
            " Karsun provide face recognition access control system with time attendance function , extension function like RFID card ,HID, QR / barcode, finger printing, palm vein/IRIS recognition, body temperature for option , management software LAN/Cloud base for option , could integrated with customer’s professional Payroll,membership management software",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
        {
          title: "​​​​​​​PARKING LOT",
          description:
            "​​​​​​​​​​​​​Karsun provide flexible solution for different countries and application parking management , like LPR parking system , UHF/Bluetooth parking system, ticket/card dispenser parking system, provide management software for parking charging payment",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
      ],
    },
    {
      productCategory: "Controllers",
      productCategoryDescription: "This is a description of Controllers",
      products: [
        {
          title: "EM ID 125 kHz W26/34 RFID reader + Digicode keypad",
          description: "This is a descrtiption of the product",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            operating_voltage: "12 V DC",
            operating_current: "less than 1000mA",
            capacity: "1600 PCS cards and PIN code",
            card_format: "M/ID /125KHz",
            reading_range: "3-10cm",
            operating_temperature: "-25°C ~ +75°C",
            access_ways: "Card, Code, Card+Code",
            waterproof_degree: "IP68",
            certifications: ["CE", "RoHS", "FCC"],
            size: "1227620(mm)",
          },
        },
        {
          title: "ASE 4 door controller",
          description: "COMING SOON",
          imageSrc: RFID,
          downloads: [],
          specs: {},
        },
      ],
    },
    {
      productCategory: "E-Gate",
      productCategoryDescription: "this is a category description",
      products: [
        {
          title: "Swing gate H306B",
          description:
            "with full stainless steel housing and special finish, our Q306W could work outdoor directly without any requirement for canopy or shelter. Arylics are used as swing arm and filling parts to make it more visual comfort. Normal and wide lane solution could be provided as per customers requirement for physically challenged people.With above features,Q306W is widely applied in places as conference centre,Office entrance,Amusement Park,Government hall,etc",
          imageSrc: RFID,
          downloads: ["link1", "link2"],
          specs: {
            "Technical Data": "test",
            "Arm Material": "test",
            "Passage width": "test",
            "Throughput rate": "test",
            "Power supply": "test",
            "Operational voltage": "test",
            "Max power consumption": "test",
            Frequency: "test",
            "Prectection level": "test",
            "Working temperature": "test",
            "Dimension excluding bars": "test",
            "Net weight including bars": "test",
          },
        },
      ],
    },
    {
      productCategory: "A.S.E Software management system ",
      productCategoryDescription:
        "this is a category description about A.S.E Software management system ",
      products: [
        {
          title: "NO SOFTWARE AVAILABLE",
          description: "COMING SOON",
          imageSrc: RFID,
          downloads: [],
          specs: {},
        },
      ],
    },
  ],
};
